version: "1.0"
services:
  server:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: server
    command: >
      sh -c "./wait-for-postgres.sh pgdb && ./main" 
    depends_on:
      - pgdb
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=pgdb
    ports:
      - 80:80
    volumes:
      - ./static:/app/static/

  pgdb:
    image: postgres:latest
    container_name: pgdb
    restart: always
    ports:
      - 5436:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data

